import Navbar from '@/components/navbar'
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/footer'
import Head from 'next/head';

export const metadata: Metadata = {
  title: 'Jofer Usa',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='overflow-x-hidden'>
      <body className='flex flex-col'>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
